import {
  LucideActivity,
  LucideArrowDownRight,
  LucideArrowLeft,
  LucideArrowRight,
  LucideArrowUpRight,
  LucideBanknote,
  LucideBell,
  LucideBuilding2,
  LucideCake,
  LucideCalendarCheck,
  LucideCalendarClock,
  LucideCalendarDays,
  LucideCalendarX,
  LucideChartColumn,
  LucideCheck,
  LucideChevronDown,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideChevronsLeft,
  LucideChevronsRight,
  LucideCircleAlert,
  LucideCircleCheck,
  LucideCircleDollarSign,
  LucideCircleQuestionMark,
  LucideCircleX,
  LucideClipboardList,
  LucideClock,
  LucideCreditCard,
  LucideDownload,
  LucideDroplet,
  LucideEllipsis,
  LucideEllipsisVertical,
  LucideExternalLink,
  LucideEye,
  LucideEyeOff,
  LucideFileText,
  LucideFlaskConical,
  LucideFolderOpen,
  LucideFunnel,
  LucideHandCoins,
  LucideHeartPulse,
  LucideIconData,
  LucideInbox,
  LucideInfo,
  LucideKeyRound,
  LucideLanguages,
  LucideLayoutDashboard,
  LucideListChecks,
  LucideLoaderCircle,
  LucideLock,
  LucideLogOut,
  LucideMail,
  LucideMapPin,
  LucideMars,
  LucideMenu,
  LucideMoon,
  LucidePanelLeft,
  LucidePencil,
  LucidePhone,
  LucidePiggyBank,
  LucidePill,
  LucidePlus,
  LucidePrinter,
  LucideReceipt,
  LucideRefreshCw,
  LucideSave,
  LucideScan,
  LucideSearch,
  LucideSearchX,
  LucideSettings,
  LucideShield,
  LucideShieldCheck,
  LucideSparkles,
  LucideStar,
  LucideStethoscope,
  LucideSun,
  LucideSyringe,
  LucideTrash2,
  LucideTrendingDown,
  LucideTrendingUp,
  LucideTriangleAlert,
  LucideUndo2,
  LucideUpload,
  LucideUserCog,
  LucideUserPlus,
  LucideUserRound,
  LucideUsers,
  LucideVenus,
  LucideWallet,
  LucideWalletMinimal,
  LucideX,
} from '@lucide/angular';

/**
 * The application's icon vocabulary.
 *
 * Icons are referenced by a stable kebab-case name rather than by importing the
 * component at every call site. That keeps navigation configs, table actions
 * and timeline entries as plain serialisable data, and it means an icon can be
 * swapped in one place. Only what is listed here is bundled.
 */
export const ICON_REGISTRY = {
  // navigation
  dashboard: LucideLayoutDashboard,
  patients: LucideUsers,
  doctors: LucideStethoscope,
  appointments: LucideCalendarDays,
  schedules: LucideCalendarClock,
  records: LucideClipboardList,
  accounts: LucideWallet,
  reports: LucideChartColumn,
  users: LucideUserCog,
  roles: LucideShieldCheck,
  settings: LucideSettings,
  notifications: LucideBell,

  // actions
  add: LucidePlus,
  edit: LucidePencil,
  delete: LucideTrash2,
  search: LucideSearch,
  filter: LucideFunnel,
  close: LucideX,
  check: LucideCheck,
  save: LucideSave,
  undo: LucideUndo2,
  download: LucideDownload,
  upload: LucideUpload,
  print: LucidePrinter,
  refresh: LucideRefreshCw,
  logout: LucideLogOut,
  more: LucideEllipsis,
  moreVertical: LucideEllipsisVertical,
  externalLink: LucideExternalLink,
  show: LucideEye,
  hide: LucideEyeOff,

  // direction
  chevronDown: LucideChevronDown,
  chevronUp: LucideChevronUp,
  chevronLeft: LucideChevronLeft,
  chevronRight: LucideChevronRight,
  chevronsLeft: LucideChevronsLeft,
  chevronsRight: LucideChevronsRight,
  arrowLeft: LucideArrowLeft,
  arrowRight: LucideArrowRight,
  trendUp: LucideArrowUpRight,
  trendDown: LucideArrowDownRight,

  // status
  success: LucideCircleCheck,
  warning: LucideTriangleAlert,
  danger: LucideCircleX,
  alert: LucideCircleAlert,
  info: LucideInfo,
  help: LucideCircleQuestionMark,
  spinner: LucideLoaderCircle,
  empty: LucideInbox,
  noResults: LucideSearchX,
  folder: LucideFolderOpen,

  // clinical
  vitals: LucideHeartPulse,
  prescription: LucidePill,
  procedure: LucideSyringe,
  lab: LucideFlaskConical,
  imaging: LucideScan,
  visit: LucideActivity,
  note: LucideFileText,
  bloodGroup: LucideDroplet,
  birthday: LucideCake,
  genderMale: LucideMars,
  genderFemale: LucideVenus,

  // contact
  phone: LucidePhone,
  mail: LucideMail,
  address: LucideMapPin,
  clinic: LucideBuilding2,

  // finance
  money: LucideBanknote,
  invoice: LucideReceipt,
  payment: LucideCreditCard,
  expense: LucideHandCoins,
  savings: LucidePiggyBank,
  balance: LucideWalletMinimal,
  currency: LucideCircleDollarSign,
  trendingUp: LucideTrendingUp,
  trendingDown: LucideTrendingDown,

  // people & scheduling
  userAdd: LucideUserPlus,
  user: LucideUserRound,
  calendarCheck: LucideCalendarCheck,
  calendarX: LucideCalendarX,
  clock: LucideClock,
  checklist: LucideListChecks,

  // chrome
  menu: LucideMenu,
  sidebar: LucidePanelLeft,
  light: LucideSun,
  dark: LucideMoon,
  language: LucideLanguages,
  lock: LucideLock,
  key: LucideKeyRound,
  shield: LucideShield,
  sparkles: LucideSparkles,
  star: LucideStar,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;

export function iconData(name: IconName): LucideIconData {
  return ICON_REGISTRY[name].icon;
}
